Fixes #3 | release tooling
allegro/marathon-appcop pull request #12
Opened 2017-04-24 14:25 UTC by tomez

2017-04-24 14:27 UTC, janisz approved these changes

2017-04-24 14:44 UTC, janisz requested changes

2017-04-24 14:44 UTC, janisz commented on .travis.yml
> +file: dist/appcop_*
I think you forgot about deploy https://docs.travis-ci.com/user/deployment/releases/

2017-04-25 07:50 UTC, tomez commented on .travis.yml
> +file: dist/appcop_*
thanks

2017-04-25 08:14 UTC, janisz approved these changes

2017-04-25 08:15 UTC, merged