Fixes #15 | Restarting apps metrics
allegro/marathon-appcop pull request #17
Opened 2017-05-09 12:04 UTC by tomez

2017-05-10 10:03 UTC, janisz requested changes

2017-05-10 10:03 UTC, janisz commented on .gitignore
> +tags
Who creates this file?

2017-05-10 10:03 UTC, janisz commented on README.md
> +appid-prefix                |                   | Prefix common to all fully qualified application ID's. Remove this preffix from applications id's (reffer to README to get an idea when this id is re
It's in readme. Add link to specific section

2017-05-10 10:03 UTC, janisz commented on config/config.go
> +		"System specific metrics. Append t o metric-prefix")
`t o` → `to`

2017-05-10 10:03 UTC, janisz commented on README.md
> +metrics-system-sub-prefix   | `appcop-internal` | System specific metrics. Append t o metric-prefix
`t o` → `to`

2017-05-10 10:03 UTC, janisz commented on marathon/app.go
> +func dropRootSlashID(data string) string {
I'd prefer [`strings.TrimPrefix`](https://golang.org/pkg/strings/#TrimPrefix) instead of this.

2017-05-10 10:03 UTC, janisz commented on marathon/app.go
> +func (t Task) GetMetric(prefix string) string {
It's not obvious what this function does. Please add a comment.

2017-05-10 10:03 UTC, janisz commented on marathon/app_test.go
> +		},
Add test with empty TaskStatus and AppId

2017-05-10 10:03 UTC, janisz commented on metrics/config.go
> +	AppSubPrefix    string
It's good time to add docs at least to the new fileds.

2017-05-10 10:03 UTC, janisz commented on marathon/marathon.go
> +		client:      pClient,
It's good time to add docs at least to the new fileds.

2017-05-10 11:17 UTC, tomez commented on .gitignore
> +tags
https://github.com/jstemmer/gotags - ctags for project, used by IDE.

2017-05-11 13:23 UTC, janisz approved these changes

2017-05-11 14:18 UTC, merged